### ISSUE TITLE
在CSS中集成icon-font

### ISSUE THREAD

**Issue by rainfore** [vusion/vusion-cli#1]
Create a postcss plugin or webpack loader that can transform svg to icon font.

Case 1 in CSS:
``` css
.select_head:after {
    icon-font: url('../icons/arrow-right.svg');
}
```
will be transformed to
``` css
@font-face {
    ...
}

.select_head:after {
    font-family: 'IconFont';
    font-style: normal;
    font-weight: normal;
    ...
    content: '\f106';
}
```

Case 2 in html:
``` html
<u-icon name="arrow-right"></u-icon>
```
```  js
import 'icons/arrow-right.svg';
```

## References:
- [icon-maker-loader](https://github.com/unimonkiez/icon-maker-loader)
- [fontgen](https://www.npmjs.com/package/fontgen-loader)
- [icons-loader](https://www.npmjs.com/package/icons-loader) has error in webpack2
- [postcss-iconfont](https://github.com/kidney/postcss-iconfont)
